/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#3f4947",
        "on-primary-container": "#91d5ce",
        "surface-tint": "#216963",
        "primary-container": "#115e59",
        "surface-container-highest": "#d3e4fe",
        error: "#ba1a1a",
        surface: "#f8f9ff",
        "on-secondary-fixed": "#00201d",
        "outline-variant": "#bec9c7",
        "inverse-surface": "#213145",
        "secondary-fixed": "#9cf2e8",
        secondary: "#006a63",
        "tertiary-fixed-dim": "#93ccff",
        "surface-container-lowest": "#ffffff",
        primary: "#004541",
        "on-tertiary-container": "#99cfff",
        "on-surface": "#0b1c30",
        "on-secondary-fixed-variant": "#00504a",
        "inverse-primary": "#8fd3cc",
        "tertiary-container": "#005988",
        "on-secondary-container": "#006f67",
        "on-primary-fixed-variant": "#00504b",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        outline: "#6f7977",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001d31",
        "secondary-container": "#99efe5",
        "secondary-fixed-dim": "#80d5cb",
        "surface-dim": "#cbdbf5",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed": "#cce5ff",
        "on-primary-fixed": "#00201e",
        background: "#f8f9ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#004b73",
        "surface-variant": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        tertiary: "#004165",
        "primary-fixed-dim": "#8fd3cc",
        "surface-container-low": "#eff4ff",
        "primary-fixed": "#abefe8",
        teal: {
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          300: "#5eead4",
          400: "#2dd4bf",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          800: "#115e59",
          900: "#134e4a",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2rem",
        "container-max": "88rem",
        "space-2xl": "3rem",
        "space-xs": "0.25rem",
        "sidebar-width": "16rem",
        "tray-width": "24rem",
        "layout-gutter": "1rem",
        "space-lg": "1.5rem",
        "space-base": "1rem",
        "space-xxs": "0.125rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
      },
      fontFamily: {
        sans: ["Manrope", "Hanken Grotesk", "system-ui", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Manrope"],
        "body-lg": ["Hanken Grotesk"],
        "title-md": ["Hanken Grotesk"],
        "headline-lg": ["Manrope"],
        "body-sm": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "display-lg-mobile": ["Manrope"],
        "metric-val": ["Hanken Grotesk"],
        "headline-sm": ["Manrope"],
        "label-md": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "title-sm": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Manrope"],
        "display-lg": ["Manrope"],
      },
    },
  },
  plugins: [],
};
